name: test_mac
on: push
jobs: 
  build:
    runs-on: macos-11
    steps: 
      - name: uname
        run: uname -m
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Install Mono
      #   run: brew install mono
      - name: Compile C# Program
        run: mcs TCPConnections~/TCPConnections.cs

      - name: download llamafile
        run: curl -L -o llamafile-0.6.2.zip https://github.com/Mozilla-Ocho/llamafile/releases/download/0.6.2/llamafile-0.6.2.zip
      - name: unzip llamafile 
        run: unzip llamafile-0.6.2.zip -d llamafile
      - name: chmod
        run: chmod -R a+rwx llamafile
      - name: download model
        run: curl -L -o model.gguf https://huggingface.co/TheBloke/phi-2-GGUF/resolve/main/phi-2.Q4_K_M.gguf?download=true
        
      - name: run command
        run: |
          sh -c "./llamafile/llamafile-0.6.2/bin/llamafile --port 13333 -m model.gguf --log-disable --nobrowser -ngl 0 --gpu no" &
          sleep 5
          netstat -lan -p tcp|grep LISTEN|grep tcp
          echo "-----------------"
          chmod +x TCPConnections~/TCPConnections.exe
          mono TCPConnections~/TCPConnections.exe
        timeout-minutes: 1